FROM openjdk:17
LABEL maintainer="benj.chu@gmail.com"
ADD target/demo-coin-web-0.0.1-SNAPSHOT.jar demo-coin-web-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "demo-coin-web-0.0.1-SNAPSHOT.jar"]
EXPOSE 8097